from typing import List, Any


class NSRunningApplication:
    def processIdentifier(self) -> int: ...
    def localizedName(self) -> str: ...


class NSWorkspace:
    @staticmethod
    def sharedWorkspace() -> "NSWorkspace": ...
    def runningApplications(self) -> List[NSRunningApplication]: ...
